### ISSUE TITLE
TWO APP CAPSTONE PROJECT -Reviewer Note

### ISSUE THREAD

**Issue by mercymugambi** [mercymugambi/backend_house_reservations_rails_app#10]
Hello, 
This group is made up of 4 people:
@mumo-esther, @joyapisi , @hasnatali1947  @mercymugambi 

[The link to the Kanban board](https://github.com/mercymugambi/appointment_booking_app/projects/1)

In this project, we are going to build the Final Capstone Project based (House Reservations Appointments).

 Kanban board screenshot below.
![kanban](https://github.com/mercymugambi/appointment_booking_app/assets/48310207/45e56b69-c525-4f80-86c5-dec56b2a490f)

**Comment by Meltrust** [comment]
Hi @mercymugambi,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, pointed, and have descriptions ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mercymugambi** [comment]
https://github.com/mercymugambi/backend_house_reservations_rails_app/issues/10
